module.exports = {
	// array
	sortedIndex: require('lodash/sortedIndex'),
	sortedIndexOf: require('lodash/sortedIndexOf'),
	// collection
	assign: require('lodash/assign'),
	each: require('lodash/each'),
	has: require('lodash/has'),
	size: require('lodash/size'),
	keys: require('lodash/keys'),
	map: require('lodash/map'),
	includes: require('lodash/includes'),
	some: require('lodash/some'),
	every: require('lodash/every'),
	values: require('lodash/values'),
	forOwn: require('lodash/forOwn'),
	// object
	create: require('lodash/create'),
	get: require('lodash/get'),
	set: require('lodash/set'),
	// function
	bind: require('lodash/bind'),
	throttle: require('lodash/throttle'),
	debounce: require('lodash/debounce'),
	spread: require('lodash/spread'),
	// string
	endsWith: require('lodash/endsWith'),
	startsWith: require('lodash/startsWith'),
	trim: require('lodash/trim'),
	// lang
	clone: require('lodash/clone'),
	cloneDeep: require('lodash/cloneDeep'),
	isArray: require('lodash/isArray'),
	isFunction: require('lodash/isFunction'),
	isNumber: require('lodash/isNumber'),
	isObject:  require('lodash/isObject'),
	isString: require('lodash/isString')
};
